import turtle
t = turtle.Turtle()
t.speed(3)
def crear_texto(mensaje,color):
    t.fillcolor(color)
    t.begin_fill()
    t.penup()
    t.goto(-170,80)
    t.pendown()
    for _ in range(2):
        t.forward(400)
        t.right(90)
        t.forward(170)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(15,55)
    t.pendown()
    t.write(mensaje, align="center",font=("Arial", 13,"bold"))
crear_texto("Tu puedes vale, esfuerzate ʕ•́ᴥ•̀ʔっ♡ Te quiero","lightpink")
t.penup()
t.goto(25,35)
t.pendown()
t.write("Te estare apoyando siempre, nunca lo dudes n.n", align="center",font=("Arial", 13,"bold"))
t.penup()
t.goto(160,-80)
t.pendown()
t.write("Con cariño: Ari", align="center",font=("Arial", 13,"bold")) 
t.penup()
t.goto(25,75)
t.pendown()
t.write("≽^•⩊•^≼", align="center",font=("Arial", 33,"bold"))
turtle.done()